const dailyQuests = [
  "Auf Zucker verzichten",
  "10 Minuten meditieren",
  "1 Glas Wasser nach dem Aufstehen trinken",
  "30 Minuten spazieren gehen",
  "1 Kapitel lesen",
  "Kein Social Media nutzen",
  "Kein Koffein nach 14 Uhr trinken",
  "Vor 22 Uhr ins Bett gehen",
  "Tagebuch schreiben",
  "5 Dinge aufschreiben, für die du dankbar bist",
  "10 Minuten dehnen",
  "Eine gesunde Mahlzeit selbst kochen",
  "Schreibtisch aufräumen",
  "15 Minuten konzentriert arbeiten",
  "Kalt duschen",
  "Zuckerfreies Frühstück essen",
  "E-Mail-Postfach aufräumen",
  "1 Person ein Kompliment machen",
  "1 Stunde ohne Bildschirm verbringen",
  "Nicht die Snooze-Taste drücken",
  "Kleiderschrank sortieren",
  "10.000 Schritte machen",
  "1 Podcast-Folge hören",
  "Plastik für einen Tag vermeiden",
  "Mit der anderen Hand Zähne putzen",
  "Eine Atemtechnik üben",
  "Bett machen nach dem Aufstehen",
  "12 Stunden ohne Bildschirmzeit am Stück",
  "Frisches Obst essen",
  "Am Abend 10 Minuten reflektieren",
  "Eine gute Tat tun",
  "Zimmerpflanzen gießen und pflegen",
  "1 Motivationsvideo ansehen",
  "Vor dem Spiegel lächeln",
  "Einen negativen Gedanken loslassen",
  "To-Do-Liste für morgen schreiben",
  "1 Stunde vor dem Schlafen Handy weglegen",
  "30 Minuten Buch statt Bildschirm",
  "Eine Affirmation laut sagen",
  "Mit jemandem telefonieren statt schreiben",
  "1 Tag vegan essen",
  "Nur Wasser trinken",
  "5 Minuten achtsames Atmen",
  "Nicht multitasken",
  "Ohne Ablenkung essen",
  "1 Kleidungsteil aussortieren",
  "1 kleine Aufgabe sofort erledigen",
  "Ziel für den Tag aufschreiben",
  "1 neue Vokabel lernen",
  "15 Minuten aufräumen",
  "Kein Junkfood essen",
  "Kaffee/Tee bewusst trinken",
  "1 inspirierendes Zitat notieren",
  "10 Minuten Yoga machen",
  "Einen alten Freund kontaktieren",
  "5 Minuten lang gar nichts tun",
  "5 Dinge aufschreiben, die gut liefen",
  "1 Aufgabe aus der Prokrastinationsliste erledigen",
  "Handy für 2 Stunden in den Flugmodus",
  "Bildschirmzeit unter 2 Stunden halten",
  "1 positive Gewohnheit notieren",
  "1 schlechte Angewohnheit beobachten",
  "Barfuß im Gras laufen",
  "Etwas Neues essen",
  "Kein Fernsehen",
  "Einen Brief oder Postkarte schreiben",
  "Auf Süßigkeiten verzichten",
  "1 YouTube Video übers Lernen oder Achtsamkeit schauen",
  "Körperhaltung bewusst verbessern",
  "Digitales Gerät reinigen",
  "1 Bild aus Kindheit ansehen",
  "Einen Sonnenaufgang oder -untergang beobachten",
  "Musik ganz bewusst hören",
  "5 Minuten draußen ohne Handy",
  "Jemandem danken",
  "Keinen Alkohol trinken",
  "Keine Nachrichten konsumieren",
  "Etwas basteln oder kreativ sein",
  "1 Sache verschenken oder spenden",
  "Weniger reden, mehr zuhören",
  "Lächeln, auch ohne Grund",
  "Aufmerksam Zähne putzen",
  "Eine kurze Meditation mit App machen",
  "Papier statt Smartphone für Notizen nutzen",
  "Handy beim Essen weglegen",
  "Mit Stift und Papier Gedanken aufschreiben",
  "Kein Fast Food essen",
  "Nur 1x pro Stunde aufs Handy schauen",
  "Etwas Neues lernen (Fakt, Tipp etc.)",
  "Einen kleinen Spaziergang direkt nach dem Essen",
  "1 Glas Wasser vor jeder Mahlzeit",
  "Keinen Fahrstuhl benutzen",
  "Warmes Getränk langsam genießen",
  "Ein Lächeln verschenken",
  "Ein Gespräch bewusst führen",
  "Lieblingslied hören und tanzen",
  "Nur 1x am Tag E-Mails checken",
  "Sich selbst loben für eine Sache",
  "1 bewusst tiefes Gespräch führen",
  "Einen ruhigen Ort aufsuchen",
  "1 neue Übung für den Körper testen",
  "Einfach mal Pause machen – ohne schlechtes Gewissen"
];
export default dailyQuests;