const extraDailyQuests = [
  "Drink only one coffee per day",
  "No sugar in coffee or tea",
  "No snacking between meals",
  "No YouTube except for learning",
  "Reply directly, no scrolling",
  "No eating on the side",
  "15 minutes of conscious non-consumption",
  "Count steps instead of scrolling",
  "Think first instead of googling",
  "Start one mini project (e.g. list, plan)",
  "Don't judge others",
  "Finish one thing instead of just starting",
  "No impulse purchases",
  "Don't leave checkout tabs open",
  "No aimless scrolling",
  "Repair or maintain one item",
  "Remember one fact consciously instead of saving it",
  "Handle paperwork for 10 minutes",
  "Prepare food yourself",
  "Do nothing during ads/loading time",
  "Pick up one thing that’s lying around",
  "Watch something mindfully for 10 minutes (no phone)",
  "Clean one area in your home deliberately",
  "10 minutes of silence (no music or podcast)",
  "Don't repeat one mistake from the day before",
  "Don't buy anything on Amazon",
  "Endure waiting without your phone",
  "Use browser without autocomplete",
  "Reflect on commute (to/from work)",
  "Initiate one small talk",
  "Consciously avoid one small talk",
  "Delete one app",
  "Disable push notifications",
  "Put smartphone on silent",
  "Don't install a new app",
  "Delete one file",
  "Rename one file properly",
  "Clean up your calendar",
  "Cancel one unnecessary appointment",
  "No double-clicking new tabs",
  "Only one tab per task",
  "No multitasking for one hour",
  "Make one decision consciously",
  "Don’t revisit completed tasks",
  "Write down a goal for the week",
  "Touch task only once (don’t procrastinate)",
  "Don’t get into pointless discussions",
  "No complaining",
  "No unnecessary explanations",
  "No justifying",
  "Don’t talk about third parties",
  "No screenshots",
  "No unnecessary bookmarks",
  "Check news only once",
  "Don’t comment – just observe",
  "Read one text fully – no skimming",
  "Tidy up before starting a new task",
  "Write one book page or note one idea",
  "One clear sentence to summarize a thought",
  "Don't plan beyond tomorrow",
  "Mind your posture (actively)",
  "Be aware of your body language",
  "Don’t interrupt",
  "Don’t compare yourself",
  "Don’t complain",
  "Leave one question unanswered (no googling)",
  "Don’t finish one podcast (discipline)",
  "Take two deep breaths before replying",
  "Track one habit",
  "Ignore one bad habit",
  "Pass on one good news",
  "Check one bill",
  "Change one password",
  "Make one simple backup (file, note)",
  "No copy-paste",
  "Do one thing analog",
  "Use the 1-minute rule (anything <1min: do it now)",
  "No background media (YouTube etc.)",
  "Visualize a goal",
  "Note one concrete next step",
  "Pause one minute before each new task",
  "Don’t reply if not necessary",
  "Activate one screen time feature",
  "Measure smartphone usage",
  "Write one sentence about yourself (reflection)",
  "Don’t like anything",
  "Don’t judge one person",
  "Don’t use one tool",
  "Make one conscious offline decision",
  "Don’t move for one minute",
  "Don’t reply to email immediately",
  "Write down a checklist for the day",
  "No excuses today",
  "Follow only one goal at a time",
  "Consciously don’t share one opinion",
  "Set one priority, ignore the rest",
  "Ask yourself one question",
  "Only shop once a day (even online)",
  "No music skipping",
  "Eat one healthy meal",
  "Refill and empty one water bottle",
  "Set one clear boundary (e.g. work time)",
  "Don’t multitask while listening",
  "Read one text properly, not diagonally",
  "Postpone one buying decision by 24h",
  "Only one window open on PC",
  "No price comparisons",
  "Review one habit from yesterday",
  "Don’t grab your phone when waiting",
  "Don’t test any new tool",
  "Cancel or simplify one meeting/call",
  "Focus on only one screen",
  "Don’t scroll old chats",
  "Don’t check for likes",
  "Declutter your calendar",
  "Don’t drift into memories",
  "Don’t evaluate yourself",
  "Don’t mentally explain things",
  "Don’t wait on standby – use the time",
  "Ignore one request (consciously, not rudely)",
  "Don’t scroll back through old conversations",
  "No 'just quickly checking'",
  "Don’t finish one thought (stop)",
  "Note a thought, don’t overthink it",
  "Don’t perfect one thing",
  "Ignore one trigger",
  "Don’t reply to old emails",
  "Only share content once",
  "Ignore all ads",
  "Note one product wish – don’t buy it",
  "Don’t comment – just read",
  "Go without smartphone completely for 1h",
  "Don’t take a screenshot",
  "Don’t save things twice",
  "Don’t read one message",
  "Don’t read in group chats",
  "Don’t wait for a reply",
  "Do one habit differently",
  "Deactivate one tool feature",
  "No multitool setup (only one app per purpose)",
  "Don’t forward anything",
  "Don’t save – decide or delete",
  "Don’t think: 'just quickly...'",
  "Plan without using time slots",
  "Don’t pursue one desire",
  "Don’t check the time",
  "Don’t justify taking a break",
  "Don’t think about productivity – just act",
  "Don’t compare yourself (no stories, no posts)",
  "No multi-channel consumption (no podcast + scrolling)",
  "Only check to-do list once per day",
  "Don’t go back to old notes",
  "Don’t jump between tabs",
  "Don’t wait for the next opportunity",
  "No podcast in the background",
  "Start one conversation – without a goal",
  "Do one thing with no purpose"
];
export default extraDailyQuests;
