const extraDailyQuests = [
  "Nur 1 Kaffee am Tag trinken",
  "Keinen Zucker im Kaffee oder Tee",
  "Kein Snack zwischen den Mahlzeiten",
  "Kein Youtube außer für Lernen",
  "Nur direkt antworten, nicht scrollen",
  "Nichts nebenbei essen",
  "15 Minuten bewusst nichts konsumieren",
  "Schritte zählen statt scrollen",
  "Statt googeln: selbst überlegen",
  "1 Mini-Projekt starten (z. B. Liste, Plan)",
  "Nicht über andere urteilen",
  "1 Sache abschließen, nicht nur anfangen",
  "Keinen Impulskauf tätigen",
  "Kein Checkout-Tab offen lassen",
  "Kein Scrollen ohne Ziel",
  "1 Gegenstand reparieren oder pflegen",
  "1 Info bewusst merken, nicht speichern",
  "Papierkram für 10 Minuten abarbeiten",
  "Essen selber zubereiten",
  "Nichts während Werbung/Loading tun",
  "1 Sache aufheben, die rumliegt",
  "10 Minuten etwas bewusst anschauen (ohne Handy)",
  "1 Ort in der Wohnung bewusst sauber machen",
  "10 Minuten Ruhe ohne Musik oder Podcast",
  "1 Fehler aus dem Vortag nicht wiederholen",
  "Kein Kauf auf Amazon",
  "Warten ohne Handy aushalten",
  "Browser ohne Autovervollständigung nutzen",
  "Weg zur Arbeit/zurück reflektieren",
  "1 Smalltalk aktiv beginnen",
  "1 Smalltalk bewusst vermeiden",
  "1 App löschen",
  "Push-Nachrichten deaktivieren",
  "Smartphone stumm schalten",
  "Neue App nicht installieren",
  "1 Datei löschen",
  "1 Datei ordentlich umbenennen",
  "Kalender aufräumen",
  "1 Termin absagen, der nicht nötig ist",
  "Kein Doppelklicken auf neue Tabs",
  "Nur 1 Tab pro Aufgabe offen",
  "1 Stunde kein Multitasking",
  "1 Entscheidung bewusst treffen",
  "Erledigte Aufgabe nicht wieder anfassen",
  "Ziel für die Woche aufschreiben",
  "Task nur 1x anfassen (nicht aufschieben)",
  "Keine unnötige Diskussion führen",
  "Nicht jammern",
  "Kein Erklärungsversuch, wenn nicht nötig",
  "Nicht rechtfertigen",
  "Nicht über Dritte reden",
  "Keinen Screenshot machen",
  "Kein unnötiges Bookmark setzen",
  "Nur 1x Nachrichten checken",
  "Nicht kommentieren, nur beobachten",
  "1 Text komplett lesen, nicht überfliegen",
  "Aufräumen, bevor neue Aufgabe beginnt",
  "1 Buch-Seite schreiben oder 1 Gedanke notieren",
  "1 klarer Satz als Gedankenzusammenfassung",
  "Nicht übermorgen planen",
  "Auf Sitzhaltung achten (aktiv)",
  "Auf Körpersprache achten",
  "Nicht unterbrechen",
  "Nicht vergleichen",
  "Nicht beschweren",
  "1 Frage offen lassen (nicht googeln)",
  "1 Podcast nicht zu Ende hören (Disziplin)",
  "Mindestens 2x tief durchatmen, bevor du antwortest",
  "1 Gewohnheit tracken",
  "1 Gewohnheit ignorieren, die schlecht ist",
  "1 gute Nachricht weitersagen",
  "1 Rechnung prüfen",
  "1 Passwort ändern",
  "1 simplen Backup machen (Datei, Notiz)",
  "Kein Copy-Paste",
  "Etwas analog machen",
  "1 Minuten-Regel nutzen (alles <1min sofort)",
  "Nichts nebenbei laufen lassen (YouTube etc.)",
  "Ziel visualisieren",
  "1 konkreten nächsten Schritt notieren",
  "1 Minute Pause vor jeder neuen Aufgabe",
  "Auf Antwort verzichten (wenn nicht nötig)",
  "1 Bildschirmzeitfunktion aktivieren",
  "Smartphone-Nutzung messen",
  "1 Satz über dich selbst aufschreiben (Reflexion)",
  "Nichts liken",
  "1 Person nicht bewerten",
  "1 Tool nicht benutzen",
  "1 bewusste Entscheidung offline treffen",
  "Sich 1 Minute nicht bewegen",
  "E-Mail nicht sofort beantworten",
  "Checkliste für den Tag notieren",
  "Heute keine Ausreden zulassen",
  "Nur 1 Ziel gleichzeitig verfolgen",
  "1 Meinung bewusst nicht äußern",
  "1 Priorität setzen, Rest ignorieren",
  "1 Frage an sich selbst stellen",
  "Nur 1x einkaufen/Tag (auch online)",
  "Kein Musik-Skippen",
  "1 gesunde Mahlzeit essen",
  "Wasserflasche auffüllen und leer trinken",
  "1 konkrete Grenze setzen (z. B. Arbeitszeit)",
  "Nicht multitasken beim Zuhören",
  "1 Text richtig durchlesen statt querlesen",
  "Kaufentscheid 24h aufschieben",
  "Nur 1 Fenster offen am PC",
  "Keine Preisvergleiche",
  "1 Gewohnheit von gestern überprüfen",
  "Nicht zum Handy greifen bei Wartezeit",
  "Kein neues Tool testen",
  "1 Meeting/Call absagen oder abspecken",
  "Sich nur auf 1 Bildschirm konzentrieren",
  "Nicht in alten Chats scrollen",
  "Nicht nach Likes schauen",
  "Kalender entrümpeln",
  "Nicht in Erinnerungen abdriften",
  "Sich nicht selbst bewerten",
  "Nicht in Gedanken erklären",
  "Nicht auf Standby warten – aktiv nutzen",
  "1 Anfrage ignorieren (bewusst, nicht unhöflich)",
  "Nicht zurückscrollen in alten Konversationen",
  "Kein “nur mal kurz schauen”",
  "1 Gedanke nicht zu Ende denken (Stopp)",
  "Gedanken notieren, nicht durchdenken",
  "1 Sache nicht perfektionieren",
  "1 Trigger ignorieren",
  "Nicht auf alte Mails antworten",
  "Nur 1x Inhalte teilen",
  "Keine Werbung anschauen",
  "1 Produktwunsch notieren, nicht kaufen",
  "Nicht kommentieren – einfach nur lesen",
  "Auf Smartphone komplett verzichten (1h)",
  "Keinen Screenshot machen",
  "Nichts doppelt speichern",
  "1 Nachricht nicht lesen",
  "Nicht in Gruppen mitlesen",
  "Nicht warten auf Antwort",
  "1 Gewohnheit anders machen",
  "1 Tool-Funktion deaktivieren",
  "Kein Multitool-Setup benutzen (nur 1 App pro Zweck)",
  "Nicht weiterleiten",
  "Nicht speichern – entscheiden oder löschen",
  "Nicht denken: „Nur kurz…“",
  "Ohne Uhrzeit planen",
  "1 Wunsch nicht verfolgen",
  "Nicht auf die Uhr schauen",
  "Sich nicht rechtfertigen für eine Pause",
  "Nicht über Produktivität nachdenken – einfach tun",
  "Sich nicht vergleichen (keine Storys, keine Posts)",
  "Kein Multichannel-Konsum (nicht Podcast + scrollen)",
  "Nur 1x pro Tag To-do-Liste ansehen",
  "Nicht zurückgehen in alten Notizen",
  "Nicht zwischen Tabs springen",
  "Nicht auf nächste Gelegenheit warten",
  "Kein Podcast im Hintergrund",
  "1 Gespräch initiieren – ohne Ziel",
  "1 Sache tun, ohne Nutzen"
];
export default extraDailyQuests;
