const items = [
    { label: "Dumbbell", value: "dumbbell", icon: "dumbbell" },
    { label: "Keyboard", value: "keyboard", icon: "keyboard" },
    { label: "Gaming", value: "youtube-gaming", icon: "youtube-gaming" },
    { label: "Meditation", value: "meditation", icon: "meditation" },
    { label: "Walking", value: "walk", icon: "walk" },
    { label: "Running", value: "run", icon: "run" },
    { label: "Yoga", value: "yoga", icon: "yoga" },
    { label: "Cooking", value: "chef-hat", icon: "chef-hat" },
    { label: "Sleep", value: "bed", icon: "bed" },
    { label: "Water", value: "cup-water", icon: "cup-water" },
    { label: "Music", value: "music", icon: "music" },
    { label: "Writing", value: "pencil", icon: "pencil" },
    { label: "Studying", value: "book", icon: "book" },
    { label: "Journal", value: "notebook", icon: "notebook" },
    { label: "Cleaning", value: "broom", icon: "broom" },
    { label: "Happy", value: "emoticon-happy", icon: "emoticon-happy" },
    { label: "Nature", value: "leaf", icon: "leaf" },
    {
      label: "Sunlight",
      value: "white-balance-sunny",
      icon: "white-balance-sunny",
    },
    { label: "Travel", value: "airplane", icon: "airplane" },
    {
      label: "Reading",
      value: "book-open-page-variant",
      icon: "book-open-page-variant",
    },
    { label: "Stretching", value: "human-handsup", icon: "human-handsup" },
    { label: "Gym", value: "weight-lifter", icon: "weight-lifter" },
    { label: "Hydration", value: "bottle-tonic", icon: "bottle-tonic" },
    {
      label: "Brush Teeth",
      value: "toothbrush-paste",
      icon: "toothbrush-paste",
    },
    { label: "Skincare", value: "face-woman", icon: "face-woman" },
    { label: "Shower", value: "shower", icon: "shower" },
    { label: "Focus", value: "target", icon: "target" },
    { label: "Productivity", value: "progress-clock", icon: "progress-clock" },
    { label: "Planner", value: "calendar-check", icon: "calendar-check" },
    { label: "Relax", value: "sofa", icon: "sofa" },
    { label: "Workout", value: "arm-flex", icon: "arm-flex" },
    { label: "Cycling", value: "bike", icon: "bike" },
    { label: "Swimming", value: "swim", icon: "swim" },
    { label: "Hiking", value: "hiking", icon: "hiking" },
    { label: "Eat Healthy", value: "food-apple", icon: "food-apple" },
    { label: "Fast Food", value: "food-off", icon: "food-off" },
    { label: "Mindfulness", value: "brain", icon: "brain" },
    { label: "Break", value: "coffee", icon: "coffee" },
    { label: "Friends", value: "account-group", icon: "account-group" },
    { label: "Family", value: "home-heart", icon: "home-heart" },
    { label: "Gratitude", value: "heart-outline", icon: "heart-outline" },
    { label: "Budgeting", value: "cash", icon: "cash" },
    { label: "Breathing", value: "lungs", icon: "lungs" },
    {
      label: "Declutter",
      value: "trash-can-outline",
      icon: "trash-can-outline",
    },
    { label: "No Sugar", value: "candy-off", icon: "candy-off" },
    {
      label: "Check-in",
      value: "check-circle-outline",
      icon: "check-circle-outline",
    },
    { label: "Wake Up", value: "alarm", icon: "alarm" },
    { label: "Bedtime", value: "clock-outline", icon: "clock-outline" },
    { label: "Energy", value: "battery-high", icon: "battery-high" },
    { label: "Creativity", value: "palette", icon: "palette" },
    { label: "Drawing", value: "draw", icon: "draw" },
    { label: "Laugh", value: "emoticon-excited", icon: "emoticon-excited" },
    { label: "Love", value: "heart", icon: "heart" },
    { label: "Volunteer", value: "hand-heart", icon: "hand-heart" },

  ];

  export default items